### ISSUE TITLE
Feature request - Dark mode 

### ISSUE THREAD

**Issue by sidgdev** [Faugus/faugus-launcher#40]
Request to add dark mode for launcher in settings

**Comment by Faugus** [comment]
Hello there.

What distro / desktop environment are you using?

**Comment by Faugus** [comment]
I released an update that improve the dark theming.
Could you please updated it and see if it's working for you?

**Comment by sidgdev** [comment]
Apologies for reaching out late. Using Fedora workstation 41 with default Gnome DE and Wayland.
I updated the launcher from repo, dark mode is working now as per system theme. 
Thanks for adding this so quick. Really enjoying it as alternative to Heroic, amazing work!

**Comment by XeniaMeraki** [comment]
On my testing on KDE with the latest Faugus Launcher flatpak dark mode system theme is still not quite respected out of the box. Could we potentially have added into gui a dark mode toggle, a few preset theme options in a dropdown menu in the settings menu?

**Comment by Faugus** [comment]
Some distros install the theme by default, some don't.
```
flatpak install org.gtk.Gtk3theme.Breeze
```
