### ISSUE TITLE
Game not properly added if DNS request is refused

### ISSUE THREAD

**Issue by 0pac1ty** [Faugus/faugus-launcher#56]
If the connection request to the used Google DNS address gets refused for any reason, the game appears to not have been added to the library while still being added in the background. The same game can't be added twice while in this state as it already exists. Once faugus is restarted the game is visible and can be used normally.

```
Traceback (most recent call last):
  File "/usr/bin/faugus-launcher", line 1759, in on_dialog_response
    if not check_internet_connection() and add_game_dialog.combo_box_launcher.get_active() != 0:
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/bin/faugus-launcher", line 1750, in check_internet_connection
    socket.create_connection(("8.8.8.8", 53), timeout=5)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by Faugus** [comment]
Thanks for reporting.
It should be fixed now.
Please update.

**Comment by 0pac1ty** [comment]
Thank you very much for the quick reply and adjustment. The exception still gets thrown and the game isn't getting added, though i'm unsure of why this needs to be handled this way. 

My question being: why does adding a game require a internet ping to begin with? wouldn't the same behavior as being offline make more sense if the connection gets refused?

**Comment by Faugus** [comment]
Oooh I see the problem now. You're trying to add a Linux native game, right?
It should only check the internet when installing a launcher (Battle.net, EA App, Epic Games...).
I'll have to fix that.

**Comment by Faugus** [comment]
Done.

**Comment by 0pac1ty** [comment]
Not quite but that was my mistake, apologies for the missing info. 

This happens with any game/executable that is trying to get added (Windows Game in this case). I did some additional testing and this happens consistently with IP addresses which google doesn't seem to like and hence refuse the request.

I verified this test with the most recent update. The game doesn't get added and the console output is as follows:

```
Traceback (most recent call last):
  File "/usr/bin/faugus-launcher", line 1728, in on_dialog_response
    if not check_internet_connection() and add_game_dialog.combo_box_launcher.get_active() != 0 and add_game_dialog.combo_box_launcher.get_active() != 1:
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/bin/faugus-launcher", line 1719, in check_internet_connection
    socket.create_connection(("8.8.8.8", 53), timeout=5)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/socket.py", line 864, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.13/socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by Faugus** [comment]
What distro are you running?

**Comment by Faugus** [comment]
I just pushed an update and now it should not test the internet connection when adding a windows or linux game.
Please let me know if you're still facing this issue.

**Comment by 0pac1ty** [comment]
This was using Arch on Kernel 6.12.7. While i was typing my reply you already responded with the fix.
Can confirm this fixes the issue and no more exceptions get thrown. Thank you very much for the quick replies and updates. Happy (soon) New Years!

**Comment by Faugus** [comment]
Thanks for reporting and testing.
Happy new year for you too!
Enjoy the app!
